# Generated by Django 5.0.4 on 2024-05-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0004_delete_usercomments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reservationTime',
            field=models.SmallIntegerField(default=10),
        ),
    ]
