# Generated by Django 5.0.4 on 2024-05-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0005_booking_reservationtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='reservationTime',
            new_name='bookingTime',
        ),
    ]
